"""initial_enterprise_schema

Revision ID: d5df7dcba761
Revises: 
Create Date: 2026-09-05 15:49:52.270612

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5df7dcba761'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_external_id'), 'projects', ['external_id'], unique=True)
    op.create_table('technologies',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=64), nullable=False),
    sa.Column('end_of_support', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_external_id'), 'technologies', ['external_id'], unique=True)
    op.create_table('applications',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('business_unit', sa.String(length=255), nullable=True),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('criticality', sa.Enum('critical', 'high', 'medium', 'low', name='criticality_enum'), nullable=False),
    sa.Column('environment', sa.Enum('production', 'staging', 'development', 'test', 'dr', name='environment_name_enum'), nullable=False),
    sa.Column('deployment_model', sa.Enum('on_prem', 'cloud', 'hybrid', 'mainframe', 'saas', name='deployment_model_enum'), nullable=False),
    sa.Column('age_years', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'external_id', name='uq_applications_project_external_id')
    )
    op.create_index(op.f('ix_applications_external_id'), 'applications', ['external_id'], unique=False)
    op.create_index(op.f('ix_applications_project_id'), 'applications', ['project_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'import', 'analyze', 'recommend', 'approve', 'reject', 'modify', name='audit_action_enum'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('source_asset_type', sa.Enum('application', 'service', 'database', 'api', 'infrastructure', name='asset_type_enum'), nullable=False),
    sa.Column('source_external_id', sa.String(length=64), nullable=False),
    sa.Column('target_asset_type', sa.Enum('application', 'service', 'database', 'api', 'infrastructure', name='asset_type_enum'), nullable=False),
    sa.Column('target_external_id', sa.String(length=64), nullable=False),
    sa.Column('dependency_type', sa.Enum('calls', 'reads_from', 'writes_to', 'depends_on', 'publishes_to', 'consumes_from', name='dependency_type_enum'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('traffic_per_day', sa.Float(), nullable=True),
    sa.Column('criticality', sa.Enum('critical', 'high', 'medium', 'low', name='criticality_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'external_id', name='uq_dependencies_project_external_id')
    )
    op.create_index(op.f('ix_dependencies_external_id'), 'dependencies', ['external_id'], unique=False)
    op.create_index(op.f('ix_dependencies_project_id'), 'dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_dependencies_source_external_id'), 'dependencies', ['source_external_id'], unique=False)
    op.create_index(op.f('ix_dependencies_target_external_id'), 'dependencies', ['target_external_id'], unique=False)
    op.create_table('documents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.String(length=128), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'external_id', name='uq_documents_project_external_id')
    )
    op.create_index(op.f('ix_documents_external_id'), 'documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_external_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_table('infrastructure_resources',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_resources_external_id'), 'infrastructure_resources', ['external_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_resources_project_id'), 'infrastructure_resources', ['project_id'], unique=False)
    op.create_table('migration_waves',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'wave_number', name='uq_migration_waves_project_number')
    )
    op.create_index(op.f('ix_migration_waves_external_id'), 'migration_waves', ['external_id'], unique=False)
    op.create_index(op.f('ix_migration_waves_project_id'), 'migration_waves', ['project_id'], unique=False)
    op.create_table('api_assets',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('base_path', sa.String(length=512), nullable=True),
    sa.Column('auth_method', sa.String(length=128), nullable=True),
    sa.Column('average_latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_assets_application_id'), 'api_assets', ['application_id'], unique=False)
    op.create_index(op.f('ix_api_assets_external_id'), 'api_assets', ['external_id'], unique=False)
    op.create_table('cost_estimates',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('one_time_low', sa.Float(), nullable=False),
    sa.Column('one_time_base', sa.Float(), nullable=False),
    sa.Column('one_time_high', sa.Float(), nullable=False),
    sa.Column('monthly_low', sa.Float(), nullable=False),
    sa.Column('monthly_base', sa.Float(), nullable=False),
    sa.Column('monthly_high', sa.Float(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=False),
    sa.Column('breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_estimates_application_id'), 'cost_estimates', ['application_id'], unique=False)
    op.create_index(op.f('ix_cost_estimates_external_id'), 'cost_estimates', ['external_id'], unique=False)
    op.create_table('database_assets',
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('database_type', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('size_gb', sa.Float(), nullable=True),
    sa.Column('table_count', sa.Integer(), nullable=True),
    sa.Column('daily_growth_gb', sa.Float(), nullable=True),
    sa.Column('criticality', sa.Enum('critical', 'high', 'medium', 'low', name='criticality_enum'), nullable=False),
    sa.Column('contains_sensitive_data', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_assets_application_id'), 'database_assets', ['application_id'], unique=False)
    op.create_index(op.f('ix_database_assets_external_id'), 'database_assets', ['external_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_doc_index'),
    sa.UniqueConstraint('evidence_id', name='uq_document_chunks_evidence_id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_evidence_id'), 'document_chunks', ['evidence_id'], unique=False)
    op.create_table('migration_recommendations',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.Enum('rehost', 'replatform', 'refactor', 'repurchase', 'retire', 'retain', 'replace', name='modernization_strategy_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('risks_summary', sa.Text(), nullable=True),
    sa.Column('alternatives', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'modified', name='recommendation_status_enum'), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_recommendations_application_id'), 'migration_recommendations', ['application_id'], unique=False)
    op.create_index(op.f('ix_migration_recommendations_external_id'), 'migration_recommendations', ['external_id'], unique=False)
    op.create_table('migration_wave_memberships',
    sa.Column('wave_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('prerequisites', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('blockers', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wave_id'], ['migration_waves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wave_id', 'application_id', name='uq_wave_membership_app')
    )
    op.create_index(op.f('ix_migration_wave_memberships_application_id'), 'migration_wave_memberships', ['application_id'], unique=False)
    op.create_index(op.f('ix_migration_wave_memberships_wave_id'), 'migration_wave_memberships', ['wave_id'], unique=False)
    op.create_table('risks',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('technical', 'operational', 'security', 'compliance', 'data', 'dependency', 'business', 'migration_complexity', name='risk_category_enum'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='risk_severity_enum'), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_application_id'), 'risks', ['application_id'], unique=False)
    op.create_index(op.f('ix_risks_external_id'), 'risks', ['external_id'], unique=False)
    op.create_table('services',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=True),
    sa.Column('framework', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('replicas', sa.Integer(), nullable=True),
    sa.Column('deployment_environment', sa.Enum('production', 'staging', 'development', 'test', 'dr', name='environment_name_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_application_id'), 'services', ['application_id'], unique=False)
    op.create_index(op.f('ix_services_external_id'), 'services', ['external_id'], unique=False)
    op.create_table('approvals',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'modified', name='approval_decision_enum'), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('original_strategy', sa.String(length=64), nullable=True),
    sa.Column('modified_strategy', sa.String(length=64), nullable=True),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['migration_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_recommendation_id'), 'approvals', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_recommendation_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_services_external_id'), table_name='services')
    op.drop_index(op.f('ix_services_application_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_risks_external_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_application_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_migration_wave_memberships_wave_id'), table_name='migration_wave_memberships')
    op.drop_index(op.f('ix_migration_wave_memberships_application_id'), table_name='migration_wave_memberships')
    op.drop_table('migration_wave_memberships')
    op.drop_index(op.f('ix_migration_recommendations_external_id'), table_name='migration_recommendations')
    op.drop_index(op.f('ix_migration_recommendations_application_id'), table_name='migration_recommendations')
    op.drop_table('migration_recommendations')
    op.drop_index(op.f('ix_document_chunks_evidence_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_database_assets_external_id'), table_name='database_assets')
    op.drop_index(op.f('ix_database_assets_application_id'), table_name='database_assets')
    op.drop_table('database_assets')
    op.drop_index(op.f('ix_cost_estimates_external_id'), table_name='cost_estimates')
    op.drop_index(op.f('ix_cost_estimates_application_id'), table_name='cost_estimates')
    op.drop_table('cost_estimates')
    op.drop_index(op.f('ix_api_assets_external_id'), table_name='api_assets')
    op.drop_index(op.f('ix_api_assets_application_id'), table_name='api_assets')
    op.drop_table('api_assets')
    op.drop_index(op.f('ix_migration_waves_project_id'), table_name='migration_waves')
    op.drop_index(op.f('ix_migration_waves_external_id'), table_name='migration_waves')
    op.drop_table('migration_waves')
    op.drop_index(op.f('ix_infrastructure_resources_project_id'), table_name='infrastructure_resources')
    op.drop_index(op.f('ix_infrastructure_resources_external_id'), table_name='infrastructure_resources')
    op.drop_table('infrastructure_resources')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_external_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dependencies_target_external_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_source_external_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_project_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_external_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_applications_project_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_external_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_technologies_external_id'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_projects_external_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
